auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: maxwellxxx's Blog
url: http://www.maxwellxxx.com
feed: /atom.xml
author_info: <a href="http://www.maxwellxxx.com/">maxwellxxx</a>
